# Generated by Django 5.1.3 on 2024-11-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='compiled',
            new_name='completed',
        ),
    ]
