# Generated by Django 5.1.3 on 2024-11-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_rename_compiled_todo_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
